// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from './application'

import MapController from './map_controller'
application.register('map', MapController)
