---
EnableDefaultLinters: true
exclude:
  - '**/vendor/**/*'
linters:
  PartialInstanceVariable:
    enabled: true
    exclude:
      # needed until https://github.com/Shopify/erb-lint/pull/235 is merged and released
      - '**/app/views/devise/mailer/*.html.erb'
      - '**/app/views/territory_categories/index.html.erb'
      - '**/app/views/territory_categories/show.html.erb'
  DeprecatedClasses:
    enabled: true
  ErbSafety:
    enabled: true
    exclude:
      - '**/app/views/territories/_geometry.html.erb' # Use inline disable comment once https://github.com/Shopify/erb-lint/pull/249 is merged
  RequireScriptNonce:
    enabled: true
    exclude:
      - '**/app/views/territories/_geometry.html.erb' # Use inline disable comment once https://github.com/Shopify/erb-lint/pull/249 is merged
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
