---
EnableDefaultLinters: true
exclude:
  - '**/vendor/**/*'
  - 'app/views/application/_favicon.html.erb'
linters:
  PartialInstanceVariable:
    enabled: true
    exclude:
      - '**/app/views/layouts/_header.html.erb'
  DeprecatedClasses:
    enabled: true
  ErbSafety:
    enabled: true
    exclude:
      # Use inline disable comment once https://github.com/Shopify/erb-lint/pull/249 is merged
      - '**/app/views/territories/_geometry.html.erb'
      - '**/app/views/layouts/_sentry.html.erb'
  RequireScriptNonce:
    enabled: true
    exclude:
      # Use inline disable comment once https://github.com/Shopify/erb-lint/pull/249 is merged
      - '**/app/views/territories/_geometry.html.erb'
      - '**/app/views/layouts/_sentry.html.erb'
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Style/Semicolon:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
