default:
  image: ruby:3.1.2
  tags:
    - xuan # We use our own runner: faster and the shared seem to have a network issue

variables:
  GITLAB_CI_POSTGRES_HOST: postgis-postgis
  GITLAB_CI_POSTGRES_DB: gxis_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  SAST_EXCLUDED_PATHS: vendor

.ruby:
  cache:
    key:
      files:
        - Gemfile.lock
    paths:
      - vendor/ruby
  before_script:
    - bundle config set --local path 'vendor/ruby'
    - bundle install

.js:
  image: node:18
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
  before_script:
    - npm install

lint-rb:
  extends: .ruby
  stage: test
  script:
    - make lint-rb

lint-js:
  extends: .js
  stage: test
  script:
    - make lint-js

test-unit:
  extends: .ruby
  stage: test
  services:
    - postgis/postgis:latest
  script:
    - bundle exec rails db:setup
    - make test-unit
  variables:
    MINITEST_REPORTER: JUnitReporter
    MINITEST_REPORTERS_REPORTS_DIR: test-unit
  artifacts:
    paths:
    - test-unit/*.xml
    when: always
    reports:
      junit:
      - test-unit/*.xml

test-system:
  extends: .ruby
  stage: test
  services:
    - postgis/postgis:latest
    - browserless/chrome:latest
  script:
    - bundle exec rails db:setup
    - make test-system
  variables:
    # This is needed so that chrome can access to rails server
    FF_NETWORK_PER_BUILD: 1
    MINITEST_REPORTER: JUnitReporter
    MINITEST_REPORTERS_REPORTS_DIR: test-system
  artifacts:
    paths:
      - test-system/*.xml
      # We always save the screenshots to help the debugs
      - tmp/screenshots/*
    when: always
    reports:
      junit:
        - test-system/*.xml

# Security testing (see https://gitlab.com/CodeursEnLiberte/gxis/-/security/dashboard)
include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
