default:
  image: ruby:3.0.2

services:
  - postgis/postgis:latest

variables:
  GITLAB_CI_POSTGRES_HOST: postgis-postgis
  GITLAB_CI_POSTGRES_DB: gxis_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - bundle config set --local path 'vendor/ruby'

install:
  stage: build
  script:
    - make install

lint:
  stage: test
  script:
    - make lint

test:
  stage: test
  script:
    - make test
