default:
  image: ruby:3.1.2
  tags:
    - xuan # We use our own runner: faster and the shared seem to have a network issue

services:
  - postgis/postgis:latest
  - browserless/chrome:latest

variables:
  GITLAB_CI_POSTGRES_HOST: postgis-postgis
  GITLAB_CI_POSTGRES_DB: gxis_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

install:
  stage: build
  script:
    - bundle config set --local path 'vendor/ruby'
    - make install

lint:
  stage: test
  script:
    - bundle config set --local path 'vendor/ruby'
    - make lint

test:
  stage: test
  script:
    - bundle config set --local path 'vendor/ruby'
    - bundle exec rails db:setup
    - make test
  variables:
    # This is needed so that chrome can access to rails server
    FF_NETWORK_PER_BUILD: 1
  # We always save the screenshots to help the debugs
  artifacts:
    paths:
    - /builds/CodeursEnLiberte/gxis/tmp/screenshots
    when: always
    expire_in: 1 week

# Security testing (see https://gitlab.com/CodeursEnLiberte/gxis/-/security/dashboard)
include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
