# Complete list of all available properties: https://docs.upsun.com/create-apps/app-reference.html
applications:
  cocarto:
    # Application source code directory
    source:
      root: "/"

    # The runtime the application uses.
    # Complete list of available runtimes: https://docs.upsun.com/create-apps/app-reference.html#types
    type: "ruby:3.2"

    # How many resources to devote to the app. Defaults to AUTO in production environments.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#sizes
    # size:

    # The relationships of the application with services or other applications.
    # The left-hand side is the name of the relationship as it will be exposed
    # to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
    # side is in the form `<service name>:<endpoint name>`.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#relationships
    relationships:
      postgres: "postgresql:postgresql"
      redis: "redis:redis"

    # Mounts define directories that are writable after the build is complete.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#mounts
    mounts:
       "/storage": # Represents the path in the app.
         source: "local" # "local" sources are unique to the app, while "service" sources can be shared among apps.
         source_path: "storage" # The subdirectory within the mounted disk (the source) where the mount should point.
       "/tmp": # Represents the path in the app.
         source: "local" # "local" sources are unique to the app, while "service" sources can be shared among apps.
         source_path: "tmp" # The subdirectory within the mounted disk (the source) where the mount should point.
       "/log": # Represents the path in the app.
         source: "local" # "local" sources are unique to the app, while "service" sources can be shared among apps.
         source_path: "log" # The subdirectory within the mounted disk (the source) where the mount should point.

    # The web key configures the web server running in front of your app.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#web
    web:
      # Commands are run once after deployment to start the application process.
      # More information: https://docs.upsun.com/create-apps/app-reference.html#web-commands
      commands:
        # The command to launch your app. If it terminates, it’s restarted immediately.
        # You can use the $PORT or the $SOCKET environment variable depending on the socket family of your upstream
        start: "bundle exec rails s"
      # Each key in locations is a path on your site with a leading /.
      # More information: https://docs.upsun.com/create-apps/app-reference.html#locations
      locations:
        "/":
          root: 'public'
          passthru: true
    workers:
      good_job:
        commands:
        # The command to launch your app. If it terminates, it’s restarted immediately.
        # You can use the $PORT or the $SOCKET environment variable depending on the socket family of your upstream
          start: "bundle exec good_job start"

    # Alternate copies of the application to run as background processes.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#workers
    # workers:

    # The timezone for crons to run. Format: a TZ database name. Defaults to UTC, which is the timezone used for all logs
    # no matter the value here. More information: https://docs.upsun.com/create-apps/timezone.html
    # timezone: <time-zone>

    # Access control for roles accessing app environments.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#access
    # access:

    # Variables to control the environment. More information: https://docs.upsun.com/create-apps/app-reference.html#variables
    variables:
      env:
        N_PREFIX: "/app/.global"
        RAILS_ENV: "production"
        RAILS_LOG_TO_STDOUT: "true"
        # Maplibre style
        DEFAULT_MAP_STYLE: ""

        # Email setup
        PUBLIC_URL : ""
        EMAIL_FROM :  ""
        SMTP_USERNAME: ""
        SMTP_PASSWORD: ""
        SMTP_PORT : 25

        # Sentry
        SENTRY_DSN: "" # server-side ruby on rails
        SENTRY_PUBLIC_KEY: "" # client-side javascript

        # Debug flags
        COCARTO_DEBUG_SENTRY: "" # Enable Sentry in development
        COCARTO_DEBUG_SMTP: "" # Really send emails SMTP in development
        COCARTO_DEBUG_WORKAROUND_HEADLESS_CHROME_WEBGL_MAC: "" # Workaround for chrome mac breaking webgl in headless

        # S3 configuration for active storage
        # Example is for a bucket called cocarto-prod on scaleway
        COCARTO_S3_ENDPOINT: https://cocarto-prod.s3.fr-par.scw.cloud
        COCARTO_S3_BUCKET: cocarto-prod
        COCARTO_S3_ACCESS_KEY:
        COCARTO_S3_SECRET_KEY:
        COCARTO_S3_REGION: fr-par


    # Outbound firewall rules for the application. More information: https://docs.upsun.com/create-apps/app-reference.html#firewall
    # firewall:

    # Specifies a default set of build tasks to run. Flavors are language-specific.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#build
    build:
      flavor: none

    # Installs global dependencies as part of the build process. They’re independent of your app’s dependencies and
    # are available in the PATH during the build process and in the runtime environment. They’re installed before
    # the build hook runs using a package manager for the language.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#dependencies
    dependencies:
      nodejs:
        n: "*"
        npx: "*"
        sharp: "*"

    # Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
    # More information: https://docs.upsun.com/create-apps/app-reference.html#hooks
    hooks:
      # The build hook is run after any build flavor.
      # More information: https://docs.upsun.com/create-apps/hooks/hooks-comparison.html#build-hook
      build: |
        set -eux
        n lts
        bundle install
        hash -r
        npm install
        bundle exec rails dartsass:build
        bundle exec rake assets:precompile
      # The deploy hook is run after the app container has been started, but before it has started accepting requests.
      # More information: https://docs.upsun.com/create-apps/hooks/hooks-comparison.html#deploy-hook
      deploy: |
        set -eux
        bundle exec rails db:migrate
        

      # The post_deploy hook is run after the app container has been started and after it has started accepting requests.
      # More information: https://docs.upsun.com/create-apps/hooks/hooks-comparison.html#deploy-hook
      # post_deploy: |

    # Scheduled tasks for the app.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#crons
    # crons:

    # Customizations to your PHP or Lisp runtime. More information: https://docs.upsun.com/create-apps/app-reference.html#runtime
    # runtime:

    # More information: https://docs.upsun.com/create-apps/app-reference.html#additional-hosts
    # additional_hosts:

# The services of the project.
#
# Each service listed will be deployed
# to power your Upsun (Staging) project.
# More information: https://docs.upsun.com/add-services.html
# Full list of available services: https://docs.upsun.com/add-services.html#available-services
services:
  postgresql:
    type: postgresql:15 # All available versions are: 15, 14, 13, 12, 11
    configuration:
        extensions:
            - postgis
  redis:
    type: redis:7.0



# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Upsun (Staging).
# More information: https://docs.upsun.com/define-routes.html
routes:
  "https://{default}/":
    type: upstream
    upstream: "cocarto:http"
  # A basic redirect definition
  # More information: https://docs.upsun.com/define-routes.html#basic-redirect-definition
  "https://www.{default}":
    type: redirect
    to: "https://{default}/"
