development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: cocarto_development
  timeout: 2.0
  reconnect_attempts: 5

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: cocarto_production
  timeout: 2.0
  reconnect_attempts: 5
